config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  
  devise_for :users
  
  resources :movies do 
    get :favorite, on: :member
    get :search, on: :collection
    # collection do
    #   get "search"
    # end
    resources :reviews, except: [ :show, :index ]
  end

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite_movie.rb
class FavoriteMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord

	include SlackNotification

	searchkick

	belongs_to :user
	has_many :favorite_movies
	has_many :favorited_by, through: :favorite_movies, source: :user # the actual users favoriting a movie
	has_many :reviews
	has_one_attached :image


	after_create :reminder

	scope :by_name, -> (keyword) { any_of({ :title => /.*#{keyword}.*/ }) if keyword.present? }
	scope :old, -> { where('year < ?', 1.years.ago )}

	def reminder
		time_str = ((self.time).localtime).strftime("%I:%M%p on %b. %d, %Y")
		message = "Movie #{self.title}. Just a reminder that you have a movie coming up at #{time_str} to watch."
		slack_data = { message: message }
		sendNotification(slack_data)
	end

	def when_to_run
		minutes_before_movie = 1.minutes
		time - minutes_before_movie
	end

	handle_asynchronously :reminder, :run_at => Proc.new { |i| i.when_to_run }

end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies
  has_many :favorite_movies
  has_many :favorites, through: :favorite_movies, source: :movie # the actual movies a user favorites
  has_many :reviews, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  include SlackNotification

  before_action :set_movie, only: %i[ show edit update destroy favorite ]
  before_action :authenticate_user!, except: [ :index, :show ]

  def search
    if params[:search].present?
      @movies = Movie.search(params[:search])
    else
      @movies= Movie.all
    end
  end

  def index
    @movies = Movie.all.by_name(name).old.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
    
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @movie = current_user.movies.build
  end

  def edit
  end

  def create
    # Time.zone = movie_params[:time_zone]
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
        message = "A new movie #{@movie.title} has been successfully Added!."

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
        message = "A new movie #{@movie.title} has been successfully Added!."
      end
      # slack_data = { message: message }
      # sendNotification(slack_data)
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def favorite
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @movie
      redirect_to movies_url, notice: "You favorited #{@movie.title}"
      message = "A new movie #{@movie.title} has been successfully Added to FAVORITES."
    elsif type == "unfavorite"
      current_user.favorites.delete(@movie)
      redirect_to movies_url, notice: "You unfavorited #{@movie.title}"
      message = "A new movie #{@movie.title} has been successfully Removed! from FAVORITES."
    else
      redirect_to movies_url, notice: "Nothing happened."
    end 

    slack_data = { message: message }
    sendNotification(slack_data)

  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :image, :year, :imdb_id, :time_zone, :time)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]
  before_action :set_movie
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to movie_url(@movie), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to movie_url(@movie), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/slack_notification.rb
module SlackNotification
  require 'slack-notifier'
  
  def sendNotification(data = {})
    slack_data        =   data.as_json
    message           =   slack_data['message']  || ''
    # channel_name = slack_data['is_psychiatrist'] ? '#admin-notifications-psychiatry' : '#admin-notifications'
    # ap "slack notification goes here ===> " + message.to_s
    if Rails.env.development?
      $notifier = Slack::Notifier.new "https://hooks.slack.com/services/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", channel: '#mayank-notifications-test', username: 'mayankbot'
      $notifier.ping message
    end
  end

end

app/views/layouts/_headers.html.erb
<div>       <%= link_to "Movie Reviews", root_path %></div>

<ul><div><% if user_signed_in? %>
          <li><%= link_to "New Movie", new_movie_path %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %></div></ul>

         <%= form_tag search_movies_path, method: :get, role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", name: nil %>
        </p>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/headers' %>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.text_field :year %>
  </div>

  <div>
    <%= form.label :imdb_id, style: "display: block" %>
    <%= form.text_field :imdb_id %>
  </div>

  <div>
    <%= form.label :movie_length, style: "display: block" %>
    <%= form.text_field :movie_length %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :time, style: "display: block" %>
    <%= form.datetime_field :time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= movie.description %>
  </p>

   <p>
    <strong>Year:</strong>
    <%= movie.year %>
  </p>

   <p>
    <strong>ImdbID:</strong>
    <%= movie.imdb_id %>
  </p>

  <p>
    <strong>Movie length:</strong>
    <%= movie.movie_length %>
  </p>

  <p>
    <strong>Director:</strong>
    <%= movie.director %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating %>
  </p>

</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>

<div id="movies">
  <% @movies.each do |movie| %>
    <%= render movie %>
    <p>
      <%= link_to "Show this movie", movie %>
    </p>
  <% end %>
</div>

<%= link_to "New movie", new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/search.html.erb
<div>
	<% @movies.each do |movie| %>

		<img src="<%= (url_for(movie.image)) %>">
	<%end%> 
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<% if @movie.image.attached? %>
<img src="<%= (url_for(@movie.image)) %>">
<% end %>

<div><p>Overall Rating</p><%= @avg_review %></div>
<em><%= "#{@reviews.count} reviews" %></em>

<div>
  <p>
    <% if current_user %>
      <%= link_to "favorite",   favorite_movie_path(@movie, type: "favorite") %>
      <%= link_to "unfavorite", favorite_movie_path(@movie, type: "unfavorite") %>
    <% end %>

  </p>
</div>

<%= render @movie %>

<div>
  <h1>Reviews</h1>
  <h2><%= @movie.title %></h2>
  <p><%= @movie.description %></p>

  <% if @reviews.blank? %>
  <h3>Write a first review</h3>
  <%= link_to "write a review", new_movie_review_path(@movie)%>
  <% else %>
  <% @reviews.each do |review|%>
  <p><%= review.rating %></p>
  <p><%= review.comment %></p>
  <% end %>
  <% end %>

</div>
<div>
  <%= link_to "Write a Review", new_movie_review_path(@movie) %> |
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |form| %>
  <% if review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= review.comment %>
  </p>

</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", movie_path(@movie) %>
</div>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<div id="reviews">
  <% @reviews.each do |review| %>
    <%= render review %>
    <p>
      <%= link_to "Show this review", "#" %>
    </p>
  <% end %>
</div>

<%= link_to "New review", new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", movie_path(@movie) %>
</div>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<div>
  <%= link_to "Edit this review", edit_review_path(@review) %> |
  <%= link_to "Back to reviews", "#" %>

<p>
  <%= @review.user.email %>
</p>

  <%= button_to "Destroy this review", @review, method: :delete %>
</div>